package exception;
class Exception
{
   public static void main(String args[])
   {
      try{
         int a=1,b=0;
         int c=a/b;
         System.out.println ("Result: "+c);
      }
      catch(ArithmeticException e){
         System.out.println ("EXCEPTIONAL HANDLING PERFORMED");
      }
   }
}
